services:
  db:
    container_name: db
    image: postgres:14-alpine
    hostname: db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    # To get a tuned database for large loads:
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./configs/postgres.largedb.conf:/etc/postgresql/postgresql.conf
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
